//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:CatererService/Caterer/CatererPackages.aspx.designer.cs
namespace CatererService.Caterer
{


    public partial class CatererPackages
    {

        /// <summary>
        /// DataList1 control.
=======
namespace CatererService.Pages.Admins
{


    public partial class Report_admin_
    {

        /// <summary>
        /// GridView1 control.
>>>>>>> 9f755879e2228b0383267bbdc400c11f38117f96:CatererService/Pages/Admins/Report(admin).aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD:CatererService/Caterer/CatererPackages.aspx.designer.cs
        protected global::System.Web.UI.WebControls.DataList DataList1;

        /// <summary>
        /// SqlDS_PackagesList control.
=======
        protected global::System.Web.UI.WebControls.GridView GridView1;

        /// <summary>
        /// Sqlreport control.
>>>>>>> 9f755879e2228b0383267bbdc400c11f38117f96:CatererService/Pages/Admins/Report(admin).aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD:CatererService/Caterer/CatererPackages.aspx.designer.cs
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDS_PackagesList;
=======
        protected global::System.Web.UI.WebControls.SqlDataSource Sqlreport;
>>>>>>> 9f755879e2228b0383267bbdc400c11f38117f96:CatererService/Pages/Admins/Report(admin).aspx.designer.cs
    }
}
